---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pomelo-nas-pv
  labels:
    app: pomelo
spec:
  capacity:
    storage: 100Gi
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: pomelo-nas-pv
    volumeAttributes:
      server: "382934934e-qpp34.cn-shanghai.nas.aliyuncs.com"
      path: "/kf/docs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pomelo-storage
  namespace: <NAMESPACE>
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      app: pomelo
