"""remove_approval_system

Revision ID: 5e0b48d4d4f1
Revises: 717687cd77b3
Create Date: 2026-08-01 19:53:43.840039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5e0b48d4d4f1'
down_revision: Union[str, None] = '717687cd77b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_ibfk_3', 'documents', type_='foreignkey')
    op.drop_table('approval_steps')
    op.drop_table('approval_processes')
    op.drop_table('rewrite_styles')
    op.drop_table('backup_records')
    op.add_column('documents', sa.Column('path', sa.String(length=500), nullable=False))
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'original_path')
    op.drop_column('documents', 'approval_process_id')
    op.drop_column('documents', 'approved_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('approved_path', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('documents', sa.Column('approval_process_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('original_path', mysql.VARCHAR(length=500), nullable=False))
    op.add_column('documents', sa.Column('status', mysql.ENUM('STAGE', 'APPROVED', 'REJECTED'), nullable=False))
    op.drop_column('documents', 'path')
    op.create_table('backup_records',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('library_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('backup_path', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('content_hash', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('file_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='backup_records_ibfk_1'),
    sa.ForeignKeyConstraint(['library_id'], ['document_libraries.id'], name='backup_records_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rewrite_styles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('prompt', mysql.TEXT(), nullable=False),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('approval_processes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('library_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('temp_dir', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('locked_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('locked_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='approval_processes_ibfk_1'),
    sa.ForeignKeyConstraint(['library_id'], ['document_libraries.id'], name='approval_processes_ibfk_2'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], name='approval_processes_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('approval_steps',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('process_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('step_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('step_data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['process_id'], ['approval_processes.id'], name='approval_steps_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_approval_steps_process_id', 'approval_steps', ['process_id'], unique=False)
    op.create_foreign_key('documents_ibfk_3', 'documents', 'approval_processes', ['approval_process_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
