"""add_ondelete_cascade

Revision ID: 717687cd77b3
Revises: cfb7ca1d100f
Create Date: 2026-08-01 17:35:39.891998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717687cd77b3'
down_revision: Union[str, None] = 'cfb7ca1d100f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('approval_steps_ibfk_1', 'approval_steps', type_='foreignkey')
    op.create_foreign_key(None, 'approval_steps', 'approval_processes', ['process_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('documents_ibfk_3', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'approval_processes', ['approval_process_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_ibfk_3', 'documents', 'approval_processes', ['approval_process_id'], ['id'])
    op.drop_constraint(None, 'approval_steps', type_='foreignkey')
    op.create_foreign_key('approval_steps_ibfk_1', 'approval_steps', 'approval_processes', ['process_id'], ['id'])
    # ### end Alembic commands ###
