"""add_prompt_text_to_qb

Revision ID: a218e4d82bfe
Revises: 1382e9d14ecb
Create Date: 2026-08-09 15:09:58.049378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a218e4d82bfe'
down_revision: Union[str, None] = '1382e9d14ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('qb', sa.Column('prompt_text', sa.Text(), nullable=False, server_default=sa.text("''")))
    # backfill existing QBs from their AIPrompt
    op.execute("""
        UPDATE qb SET prompt_text = (
            SELECT prompt FROM ai_prompts WHERE ai_prompts.id = qb.prompt_id
        ) WHERE prompt_id IS NOT NULL AND prompt_text = ''
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qb', 'prompt_text')
    op.alter_column('exams', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('exam_batches', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
