"""add_approval_process_id_to_documents

Revision ID: cfb7ca1d100f
Revises: 64765a6e5931
Create Date: 2026-08-01 14:46:06.593526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfb7ca1d100f'
down_revision: Union[str, None] = '64765a6e5931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('approval_process_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'approval_processes', ['approval_process_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'approval_process_id')
    # ### end Alembic commands ###
